const REGEX_DIRECTORIES_TO_BE_ADDED_HERE = "veterinaire|" +
"comportement-chien|"+
"accessoires-chien|"+
"alimentation-chien|"+
"races-de-chien|"+
"bienetre-chien|"+
"croquettes-chien\/bi-nutrition-chien|"+
"croquettes-chien\/cendre-mineraux-croquette|"+
"croquettes-chien\/chien-diabetique|"+
"croquettes-chien\/conservation-croquette|"+
"croquettes-chien\/croquette-bio|"+
"croquettes-chien\/croquette-chien-sterilise|"+
"croquettes-chien\/croquette-chiot|"+
"croquettes-chien\/croquette-grand-chien|"+
"croquettes-chien\/croquette-light|"+
"croquettes-chien\/croquette-petit-chien|"+
"croquettes-chien\/croquette-quantite|"+
"croquettes-chien\/croquette-sans-cereales|"+
"croquettes-chien\/croquette-sans-gluten|"+
"croquettes-chien\/croquette-senior|"+
"croquettes-chien\/croquettes-vegan|"+
"croquettes-chien\/digestion-sensible|"+
"croquettes-chien\/etiquette-croquette|"+
"croquettes-chien\/glucide-croquette|"+
"croquettes-chien\/mycotoxines-croquette|"+
"croquettes-chien\/orijen|"+
"croquettes-chien\/peau-sensible|"+
"croquettes-chien\/proteine-croquette|"+
'croquettes\-chien\/croquette\-akita\-americain|'+
'croquettes\-chien\/croquette\-akita\-inu|'+
'croquettes\-chien\/croquette\-american\-bully|'+
'croquettes\-chien\/croquette\-american\-staff|'+
'croquettes\-chien\/croquette\-barzoi|'+
'croquettes\-chien\/croquette\-basenji|'+
'croquettes\-chien\/croquette\-berger\-anatolie|'+
'croquettes\-chien\/croquette\-berger\-blanc\-suisse|'+
'croquettes\-chien\/croquette\-berger\-des\-pyrenees|'+
'croquettes\-chien\/croquette\-berger\-du\-caucase|'+
'croquettes\-chien\/croquette\-berger\-holandais|'+
'croquettes\-chien\/croquette\-berger\-shetland|'+
'croquettes\-chien\/croquette\-bichon\-havanais|'+
'croquettes\-chien\/croquette\-bichon\-maltais|'+
'croquettes\-chien\/croquette\-border\-terrier|'+
'croquettes\-chien\/croquette\-bouledogue\-americain|'+
'croquettes\-chien\/croquette\-bouledogue\-anglais|'+
'croquettes\-chien\/croquette\-braque\-allemand|'+
'croquettes\-chien\/croquette\-braque\-auvergne|'+
'croquettes\-chien\/croquette\-braque\-hongrois|'+
'croquettes\-chien\/croquette\-braque\-weimar|'+
'croquettes\-chien\/croquette\-bullmastiff|'+
'croquettes\-chien\/croquette\-caniche|'+
'croquettes\-chien\/croquette\-chien\-loup\-tchecoslovaque|'+
'croquettes\-chien\/croquette\-chow\-chow|'+
'croquettes\-chien\/croquette\-cocker\-americain|'+
'croquettes\-chien\/croquette\-colley|'+
'croquettes\-chien\/croquette\-coton\-tulear|'+
'croquettes\-chien\/croquette\-dalmatien|'+
'croquettes\-chien\/croquette\-dobermann|'+
'croquettes\-chien\/croquette\-dogue\-allemand|'+
'croquettes\-chien\/croquette\-dogue\-de\-bordeaux|'+
'croquettes\-chien\/croquette\-dogue\-tibet|'+
'croquettes\-chien\/croquette\-epagneul\-breton|'+
'croquettes\-chien\/croquette\-epagneul\-tibetain|'+
'croquettes\-chien\/croquette\-eurasier|'+
'croquettes\-chien\/croquette\-fila\-brasileiro|'+
'croquettes\-chien\/croquette\-fox\-terrier|'+
'croquettes\-chien\/croquette\-greyhound|'+
'croquettes\-chien\/croquette\-griffon\-korthals|'+
'croquettes\-chien\/croquette\-komondor|'+
'croquettes\-chien\/croquette\-leonberger|'+
'croquettes\-chien\/croquette\-lhassa\-apso|'+
'croquettes\-chien\/croquette\-malamute|'+
'croquettes\-chien\/croquette\-mastiff|'+
'croquettes\-chien\/croquette\-matin\-naples|'+
'croquettes\-chien\/croquette\-patou|'+
'croquettes\-chien\/croquette\-pekinois|'+
'croquettes\-chien\/croquette\-petit\-levrier\-italien|'+
'croquettes\-chien\/croquette\-pinscher\-nain|'+
'croquettes\-chien\/croquette\-pitbull|'+
'croquettes\-chien\/croquette\-pointer\-anglais|'+
'croquettes\-chien\/croquette\-pomsky|'+
'croquettes\-chien\/croquette\-porcelaine|'+
'croquettes\-chien\/croquette\-saint\-bernard|'+
'croquettes\-chien\/croquette\-samoyede|'+
'croquettes\-chien\/croquette\-schnauzer\-nain|'+
'croquettes\-chien\/croquette\-setter\-anglais|'+
'croquettes\-chien\/croquette\-setter\-gordon|'+
'croquettes\-chien\/croquette\-setter\-irlandais|'+
'croquettes\-chien\/croquette\-shiba\-inu|'+
'croquettes\-chien\/croquette\-shih\-tzu|'+
'croquettes\-chien\/croquette\-spit\-japonais|'+
'croquettes\-chien\/croquette\-spitz\-allemand|'+
'croquettes\-chien\/croquette\-spitz\-nain|'+
'croquettes\-chien\/croquette\-springer\-spaniel|'+
'croquettes\-chien\/croquette\-teckel|'+
'croquettes\-chien\/croquette\-tosa|'+
'croquettes\-chien\/croquette\-welsh\-corgi|'+
'croquettes\-chien\/croquette\-westie|'+
'croquettes\-chien\/croquette\-whippet|'+
"croquettes-chien\/royal-canin";

const REGEX_TRANSPARENT_TO_WF = "race\-chien";


// https://www.hectorkitchen.com/institute/sante-chien/ -> https://www.hectorkitchen.com/sante-chien/

const REGEX_INTERNALREDIRECTIONS_TO_BE_ADDED_HERE = `institute\/(?<page>sante-chien|adoption-chien|bien-etre-chien|comportement-chien|races-de-chien|accessoires-chien)`;

const REGEX_MIGRATION_INTERNAL_TO_BE_ADDED_HERE =
"?<page>sante-chien|"+
"adoption-chien|"+
"accessoires-chien|"+
"races-de-chien|"+
"alimentation-chien|"+
"croquettes\-chien\/croquette\-beagle\/?|"+
"croquettes\-chien\/croquette\-beauceron\/?|"+
"croquettes\-chien\/croquette\-berger-allemand\/?|"+
"croquettes\-chien\/croquette\-berger-australien\/?|"+
"croquettes\-chien\/croquette\-border-collie\/?|"+
"croquettes\-chien\/croquette\-bouvier-bernois\/?|"+
"croquettes\-chien\/croquette\-boxer\/?|"+
"croquettes\-chien\/croquette\-bull-terrier\/?|"+
"croquettes\-chien\/croquette\-cane-corso\/?|"+
"croquettes\-chien\/croquette\-carlin\/?|"+
"croquettes\-chien\/croquette\-cavalier-king-charles\/?|"+
"croquettes\-chien\/croquette\-chihuahua\/?|"+
"croquettes\-chien\/croquette\-cocker-anglais\/?|"+
"croquettes\-chien\/croquette\-dogue-argentin\/?|"+
"croquettes\-chien\/croquette\-golden-retriever\/?|"+
"croquettes\-chien\/croquette\-husky\/?|"+
"croquettes\-chien\/croquette\-jack-russel\/?|"+
"croquettes\-chien\/croquette\-malinois\/?|"+
"croquettes\-chien\/croquette\-rottweiler\/?|"+
"croquettes\-chien\/croquette\-sharpei\/?|"+
"croquettes\-chien\/croquette\-staffie\/?|"+
"croquettes\-chien\/croquette\-terre-neuve\/?|"+
"croquettes\-chien\/croquette\-yorkshire\/?|"+
"croquettes\-chien\/croquettes\-bouledogue-francais\/?|"+
"croquettes\-chien\/croquettes\-labrador\/?|"+
"croquettes\-chien\/croquettes\-pressees-froid\/?"
"bien-etre-chien";

const MIGRATION_EXCEPTIONS =
"juststartregex|"+
"alimentation-chienne-allaitante";

const REGEX_MIGRATIONS_SANTE_CHIEN_TO_BE_ADDED_HERE =
"saillie-chien|"+
"nettoyer-oreille-chien|"+
"toux-de-chenil|"+
"aloe-vera-chien|"+
"vomissement-chien|"+
"chien-bave|"+
"demodecie-chien|"+
"parvovirose-chien|"+
"osteopathe-chien|"+
"bouton-chien|"+
"vitamine-chien|"+
"tomate-chien|"+
"anti-tique-chien|"+
"raisin-chien|"+
"allergie-chien|"+
"gestation-chien|"+
"chaleur-chienne|"+
"ulcere-oeil-chien|"+
"pica-chien|"+
"infection-urinaire-chien|"+
"gastrite-chien|"+
"leptospirose-chien|"+
"abces-chien|"+
"kiwi-chien|"+
"sevrage-chiot|"+
"kyste-chien|"+
"poire-chien|"+
"souffle-coeur-chien|"+
"sterilisation-chien|"+
"pomme-de-terre-chien|"+
"ail-chien|"+
"ergot-chien|"+
"gale-sarcoptique-chien|"+
"fraise-chien|"+
"mauvaise-haleine-chien|"+
"chien-tremble|"+
"homeopathie-chien|"+
"occlusion-intestinale-chien|"+
"dermatite-chien|"+
"chenille-processionnaire-chien|"+
"chien-constipe|"+
"dysplasie-hanche|"+
"antiparasitaire-chien|"+
"avc-chien|"+
"stress-chien|"+
"avocat-chien|"+
"maladie-chien|"+
"pyodermite-chien|"+
"calmant-chien|"+
"mastocytome-chien|"+
"maladie-carre-chien|"+
"tumeur-chien|"+
"melon-chien|"+
"hernie-discale-chien|"+
"pates-chien|"+
"nez-qui-coule|"+
"epillet-chien-chat|"+
"betterave-chien/|"+
"clementine-chien|"+
"hepatite-rubarth|"+
"vermifugation-chien|"+
"vers-chien|"+
"coussinet-chien|"+
"verrue-chien|"+
"puce-chien|"+
"|"+
"grossesse-nerveuse-chien|"+
"citron-chien|"+
"piqure-puce-chien|"+
"vaccin-chien|"+
"piqure-aoutat|"+
"radis-chien|"+
"anti-puce-chien|"+
"cystite-chien|"+
"gale-oreille-chien|"+
"olive-chien|"+
"chien-tousse";

// "<race>|" example: "carlin|"
const REGEX_MIGRATIONS_TO_BE_ADDED_HERE = "berger-australien|"+
"bienetre-chienbk|"+
""+
"rottweiler|"+
"beagle|"+
"beagle|"+
"berger-allemand|"+
"berger-belge-malinois|"+
"border-collie|"+
"bouledogue-francais|"+
"bouvier-bernois|"+
"cavalier-king-charles|"+
"chow\-chow|"+
"golden-retriever|"+
"husky|"+
"jack-russell|"+
"labrador|"+
"pitbull|"+
"samoyede|"+
"shiba-inu|"+
"cane-corso|"+
"carlin|"+
"shih-tzu|"+
"bichon-maltais|"+
"american-bully|"+
"eurasier|"+
"dogue-du-tibet|"+
"pinscher-nain|"+
"berger-shetland|"+
"berger-pyrenees|"+
"coton-tulear|"+
"cocker-americain|"+
"bouledogue-americain|"+
"braque-allemand|"+
"colley|"+
"fox-terrier|"+
"boxer|"+
"lhassa-apso|"+
"dogue-de-bordeaux|"+
"mastiff|"+
"basenji|"+
"staffordshire-bull-terrier|"+
"yorkshire-terrier|"+
"welsh-corgi-pembroke|"+
"berger-hollandais|"+
"berger-americain-miniature|"+
"bullmastiff|"+
"basset-hound|"+
"rhodesian-ridgeback|"+
"bichon-frise|"+
"bouvier-australien|"+
"spitz-loup|"+
"boston-terrier|"+
"bichon-havanais|"+
"springer-spaniel|"+
"whippet|"+
"bobtail|"+
"cairn-terrier|"+
"drahthaar|"+
"border-terrier|"+
"berger-belge-tervueren|"+
"briard|"+
"bouvier-flandres|"+
"schnauzer-nain|"+
"spitz-nain";


export {REGEX_DIRECTORIES_TO_BE_ADDED_HERE, 
        REGEX_INTERNALREDIRECTIONS_TO_BE_ADDED_HERE, 
        REGEX_MIGRATIONS_SANTE_CHIEN_TO_BE_ADDED_HERE,
        REGEX_MIGRATIONS_TO_BE_ADDED_HERE,
        REGEX_MIGRATION_INTERNAL_TO_BE_ADDED_HERE,
        REGEX_TRANSPARENT_TO_WF,
        MIGRATION_EXCEPTIONS
        };